server:
  port: 11000


spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/qr?allowMultiQueries=true&useSSL=false&serverTimezone=GMT%2B8&useLegacyDatetimeCode=false
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
  cloud:
    config: false

mybatis:
  mapper-locations: classpath:mapper/*.xml

mybatis-plus:
  # 实体扫描，多个package用逗号或者分号分隔
  type-aliases-package: com.dhq.entity
  configuration:
    # 这个配置会将执行的sql打印出来，在开发或测试的时候可以用
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl